image: rocm/rocm-terminal:1.6.3

variables:
  SUDO_CMD: "" # Must be "sudo" on images which dont use root user
  DEPS_DIR: "$CI_PROJECT_DIR/__dependencies"
  CMAKE_URL: "https://cmake.org/files/v3.8/cmake-3.8.1-Linux-x86_64.tar.gz"
  # General build flags
  CXXFLAGS: ""
  CMAKE_OPTIONS: ""
  # Local build options
  LOCAL_CXXFLAGS: ""
  LOCAL_CMAKE_OPTIONS: ""
  # TERM
  TERM: xterm

before_script:
  # We had to add sudo because rocm image does not use root as user
  - hipconfig
  - $SUDO_CMD apt-get update -qq
  - $SUDO_CMD apt-get install -y -qq git wget tar xz-utils bzip2 build-essential xterm
  - $SUDO_CMD apt-get install -y -qq g++ gfortran
  # cmake
  - mkdir -p $DEPS_DIR/cmake
  - wget --no-check-certificate --quiet -O - $CMAKE_URL | tar --strip-components=1 -xz -C $DEPS_DIR/cmake
  - export PATH=$DEPS_DIR/cmake/bin:$PATH
  # Combine global build options with local options
  - export CXXFLAGS=$CXXFLAGS" "$LOCAL_CXXFLAGS
  - export CMAKE_OPTIONS=$CXXFLAGS" "$LOCAL_CMAKE_OPTIONS

build:rocm:
  stage: build
  variables:
    SUDO_CMD: "sudo -E"
  script:
    - mkdir build
    - cd build
    - cmake -DBUILD_BENCHMARK=ON -DBUILD_FORTRAN_WRAPPER=ON -DBUILD_CRUSH_TEST=ON -DDEPENDENCIES_FORCE_DOWNLOAD=ON ../.
    - make -j16
    - make package
  artifacts:
    paths:
    - build/library/
    - build/test/
    - build/benchmark/
    - build/gtest/
    - build/testu01/
    - build/CMakeCache.txt
    - build/CTestTestfile.cmake
    - build/Makefile
    - build/*.deb
    - build/*.zip

test:rocm:
  stage: test
  variables:
    SUDO_CMD: "sudo -E"
  dependencies:
    - build:rocm
  script:
    - cd build
    - ctest --output-on-failure
    - ./benchmark/benchmark_rocrand_generate --dis all --engine all --trials 5
    - ./benchmark/benchmark_rocrand_kernel --dis all --engine all --trials 5
    - ./test/crush_test_rocrand --help # Just check if works

test:rocm_deb_package:
  stage: test
  variables:
    SUDO_CMD: "sudo -E"
  dependencies:
    - build:rocm
  script:
    - cd build
    - $SUDO_CMD dpkg -i rocrand-*.deb
    - mkdir ../build_package_test && cd ../build_package_test
    - cmake ../test/package/.
    - make VERBOSE=1
    - ctest --output-on-failure
    - ldd ./test_hiprand
    - $SUDO_CMD dpkg -r rocrand
